# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 626cd10bc4c6906de19604dd3ae5fe4245e098a6af4c73b63cc5b85515ee67d1de4026b7e73e18f1c77095c7d14b5e8d97b56ca26d967678b615391441a6d57d

test:
  secret_key_base: 3e233460a3a1b14ed02efc1fb655940269b56a37180e1652c51214a7f8045c12482516f954a68d4ac5d2c3dfa88880d1fe0afa9f0cfff968e2cfd1d7c957ac6e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
